### PR TITLE
Bypass CSP so web vitals script can be reliably injected

### LINKED ISSUE #65: The benchmark-web-vitals CLI script blocked by CSPs
The `benchmark-web-vitals` CLI script included in this repo attempts to [load the web-vitals library from a CDN](https://github.com/GoogleChrome/web-vitals#load-web-vitals-from-a-cdn) ([code reference](https://github.com/GoogleChromeLabs/wpp-research/blob/a58609b76f773f0ee60af32942b4f910ce45ab69/cli/commands/benchmark-web-vitals.mjs#L204-L206)) in order to collect web vitals metrics.

However, if a site has a CSP that does not allow loading scripts from an external source, the script will fail silently and only capture the Success Rate metric.

## Reproduction Steps

1. Edit the line in `benchmark-web-vitals.mjs` that launches puppeteer so it will open a non-headless version:

```js
const browser = await puppeteer.launch({ headless:false });
```

2. Try to do a benchmark of a site with a restrictive CSP, e.g.:

```
npm run research -- benchmark-web-vitals --url https://10up.com -n 1
```

3. Open the browser console of the page that is opened by puppeteer and see that the script has been blocked.

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #65.

```
$ npm run research -- benchmark-web-vitals --url 'https://10up.com/' -n 3

> wpp-research@ research /home/westonruter/repos/wpp-research
> ./cli/run.mjs "benchmark-web-vitals" "--url" "https://10up.com/" "-n" "3"

╔═══════════════════╤═══════════════════╗
║ URL               │ https://10up.com/ ║
╟───────────────────┼───────────────────╢
║ Success Rate      │ 100%              ║
╟───────────────────┼───────────────────╢
║ FCP (median)      │ 571.3             ║
╟───────────────────┼───────────────────╢
║ LCP (median)      │ 571.3             ║
╟───────────────────┼───────────────────╢
║ TTFB (median)     │ 478.3             ║
╟───────────────────┼───────────────────╢
║ LCP-TTFB (median) │ 99.1              ║
╚═══════════════════╧═══════════════════╝
```

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]

File: cli/commands/benchmark-web-vitals.mjs [hunk 1]
```diff
@@ -210,6 +210,7 @@ async function benchmarkURL( browser, params ) {
 
 	for ( requestNum = 0; requestNum < params.amount; requestNum++ ) {
 		const page = await browser.newPage();
+		await page.setBypassCSP( true ); // Bypass CSP so the web vitals script tag can be injected below.
```
Comment (joemcgill) [inline cli/commands/benchmark-web-vitals.mjs:213]: LOL. 👍🏻

**Review by joemcgill — APPROVED** [review]
